### PR TITLE
fix(admin-ui): Add full typescript type system for the SCIM plugin

### LINKED ISSUE #2124: fix(admin-ui): Add full typescript type system for the SCIM plugin
# Description

Add full typescript type system for the SCIM plugin(all files)
Except the api side which is generated from swagger

### PR DESCRIPTION
**Pull request by syntrydy**
https://github.com/GluuFederation/flex/issues/2124
closes #2124

### CODE REVIEW

**Comment by mo-auto** [comment]
### :tada: **Snyk checks have passed. No issues have been found so far.**

:white_check_mark: **security/snyk** check is complete. No issues have been found. [(View Details)](https://app.snyk.io/org/gluu-gca/pr-checks/5f9b22f4-c32d-4eb1-ad53-b4379e166f18?refs=d451778e20c2d8bac3c439783effacf4580f9fec&source=prChecksComment)

File: admin-ui/app/utils/ApiUtils.ts [hunk 1]
```diff
@@ -39,6 +39,23 @@ export function handleTypedResponse<T>(
   }
 }
 
+export function handleResponseTyped<T>(
```
Comment (moabu) [inline admin-ui/app/utils/ApiUtils.ts:42]: handleResponseTyped duplicates timeout/error handling logic found in other response helpers. Consider consolidating these functions to reduce redundancy.

Comment (moabu) [inline admin-ui/app/utils/ApiUtils.ts:42]: Two similar functions (`handleTypedResponse` and `handleResponseTyped`) exist with nearly identical logic. Consider consolidating them to reduce duplication.

File: admin-ui/plugins/scim/components/ScimConfiguration.tsx [hunk 2]
```diff
@@ -7,53 +7,70 @@ import GluuCommitDialog from 'Routes/Apps/Gluu/GluuCommitDialog'
...
     onSubmit: () => {
       toggle()
     },
   })
 
-  const submitForm = (userMessage) => {
-    const differences = []
+  const submitForm = (userMessage: string): void => {
+    const differences: ScimConfigPatchRequest[] = []
     delete formik.values?.action_message
```
Comment (moabu) [inline admin-ui/plugins/scim/components/ScimConfiguration.tsx:35]: Avoid mutatingformik.values with 'delete'. This mutation can cause unintended side effects. Consider filtering out 'action_message' in a non-mutative way (e.g. using object spread).

File: admin-ui/plugins/scim/redux/sagas/ScimSaga.ts [hunk 3]
```diff
@@ -0,0 +1,116 @@
...
+    yield put(updateToast(true, 'success'))
+    yield put(getScimConfigurationResponse(data))
+    yield call(postUserAction, audit)
+    yield* triggerWebhook({ payload: { createdFeatureValue: data } })
+    return data
+  } catch (e: unknown) {
+    const errMsg = getErrorMessage(e)
+    yield* errorToast(errMsg)
+    if (isFourZeroOneError(e)) {
+      const jwt: string = yield select((state: RootState) => state.authReducer.userinfo_jwt)
```
Comment (moabu) [inline admin-ui/plugins/scim/redux/sagas/ScimSaga.ts:73]: userinfo_jwt is typed as string|null. Add a null check before dispatching getAPIAccessToken to prevent potential issues if the JWT is missing.

File: admin-ui/plugins/scim/redux/sagas/ScimSaga.ts [hunk 4]
```diff
@@ -0,0 +1,116 @@
...
+    addAdditionalData(audit, PATCH, UPDATE_SCIM_CONFIG, payload)
+    const scimApi: SCIMConfigApi = yield* createScimApi()
+    const data: SCIMConfig = yield call(
+      scimApi.updateScimConfig,
+      payload.action.action_data as ScimConfigPatchRequestBody,
+    )
+    yield put(updateToast(true, 'success'))
+    yield put(getScimConfigurationResponse(data))
+    yield call(postUserAction, audit)
+    yield* triggerWebhook({ payload: { createdFeatureValue: data } })
```
Comment (moabu) [inline admin-ui/plugins/scim/redux/sagas/ScimSaga.ts:67]: The saga uses `yield* triggerWebhook(...)`. Ensure that `triggerWebhook` is a generator function; if not, consider using `yield call(triggerWebhook, ...)` to properly invoke it.

**Review by moabu — CHANGES_REQUESTED** [review]
The PR is missing client-side form validation in the `ScimConfiguration` component. Without a validation schema in the formik configuration, the application can send invalid data to the server, leading to unnecessary API errors and a poor user experience.

**Review by moabu — APPROVED** [review]
