### PR TITLE
fix(admin-ui): Add full typescript type system for Asset management

### LINKED ISSUE #2125: fix(admin-ui): Add full typescript type system for the SCRIPTS plugin
# Description

Add full typescript type system for the SCRIPTS plugin(all file)
Except the api side which is generated from swagger

### PR DESCRIPTION
**Pull request by syntrydy**
https://github.com/GluuFederation/flex/issues/2125
closes #2125

### CODE REVIEW

**Comment by mo-auto** [comment]
### :tada: **Snyk checks have passed. No issues have been found so far.**

:white_check_mark: **security/snyk** check is complete. No issues have been found. [(View Details)](https://app.snyk.io/org/gluu-gca/pr-checks/6fa8e8e4-b0c9-4761-825d-53259ac8436c?refs=5076269f401193a35748c8dbd9c79ff9214ae660&source=prChecksComment)

File: admin-ui/plugins/admin/components/Assets/types/ComponentTypes.ts [hunk 1]
```diff
@@ -0,0 +1,20 @@
+// Component-specific types for Asset components
```
Comment (faisalsiddique4400) [inline admin-ui/plugins/admin/components/Assets/types/ComponentTypes.ts:1]: please remove these un-necessary comments in this file

**Review by faisalsiddique4400 — APPROVED** [review]

**Review by duttarnab — APPROVED** [review]
