### PR TITLE
fix(openbanking): update the script to use the latest values.yaml 

### LINKED ISSUE #1915: fix(openbanking): update the quick install script to use the latest values.yaml configuration

### PR DESCRIPTION
**Pull request by misba7**
closes #1915

### CODE REVIEW

File: automation/startopenabankingdemo.sh [hunk 1]
```diff
@@ -92,43 +74,18 @@ global:
...
-echo -e "Testing protected endpoint /token with client crt and key. This should recieve a token, showing mTLS works \n"
-curl -X POST -k --cert client.crt --key client.key -u $TESTCLIENT:$TESTCLIENTSECRET https://demoexample.gluu.org/jans-auth/restv1/token -d grant_type=client_credentials
-echo -e "Testing protected endpoint /register without client crt and key. This should show a 403, showing mTLS works \n"
-curl -X POST -k -u $TESTCLIENT:$TESTCLIENTSECRET https://demoexample.gluu.org/jans-auth/restv1/register
-echo -e "Testing protected endpoint /register with client crt and key. This should still recieve an error but from the AS showing mTLS works \n"
-curl -X POST -k --cert client.crt --key client.key -u $TESTCLIENT:$TESTCLIENTSECRET https://demoexample.gluu.org/jans-auth/restv1/register
-cd ..
-EOF
-sudo microk8s.kubectl -n jans wait --for=condition=available --timeout=600s deploy/jans-auth-server --kubeconfig="$KUBECONFIG"
-sudo bash testendpoints.sh
```
Comment (iromli) [inline automation/startopenabankingdemo.sh:133]: Is there any reason why we remove testing endpoints?

Comment (misba7) [reply automation/startopenabankingdemo.sh:133]: Since the doc has already a complete [section](https://docs.gluu.org/head/openbanking/install-cn/#testing-the-setup) to test the setup, with multiple options, and with the steps needed
Since testing is a little bit complex in openbanking, and requires multiple steps to hit the endpoints.
So I thought this made the script cleaner, and also explicit for the client on how to test his dev setup.

Comment (moabu) [reply automation/startopenabankingdemo.sh:133]: Ok however waiting fro the setup to finish to indicate the deployment is ready should stay. Its a good indicator of the setup running.

**Review by iromli — APPROVED** [review]

**Review by moabu — APPROVED** [review]
