### PR TITLE
fix(admin-ui): The select box all over the UI is broken

### LINKED ISSUE #2240: fix(admin-ui): The select box all over the UI is broken
**Describe the bug**
The select box component all over the UI is broken.
This is due the library used for that component been too old.

**To Reproduce**

https://github.com/user-attachments/assets/700991a3-32c4-4c93-a8b7-c67ec5755d47

### PR DESCRIPTION
**Pull request by syntrydy**
https://github.com/GluuFederation/flex/issues/2240
closes #2240

### CODE REVIEW

File: admin-ui/app/routes/Apps/Gluu/GluuSelectRow.tsx [hunk 1]
```diff
@@ -56,48 +56,71 @@ function GluuSelectRow({
...
+          <Select
+            labelId={`${name}-label`}
             id={name}
             data-testid={name}
+            size="small"
             name={name}
-            defaultValue={value}
-            onChange={(event: React.ChangeEvent<HTMLInputElement | HTMLSelectElement>) => {
+            value={value || ''}
+            onChange={(event) => {
```
Comment (moabu) [inline admin-ui/app/routes/Apps/Gluu/GluuSelectRow.tsx:83]: Manually creating a synthetic event object inside the `onChange` handler is bad because it adds unnecessary complexity and boilerplate code; the original event should be used directly where possible.

File: admin-ui/app/routes/Apps/Gluu/GluuSelectRow.tsx [hunk 2]
```diff
@@ -56,48 +56,71 @@ function GluuSelectRow({
     })
   }
 
+  // Calculate grid sizes based on Bootstrap column system (out of 12)
+  const labelGridSize = Math.round((lsize / 12) * 12)
+  const selectGridSize = Math.round((rsize / 12) * 12)
```
Comment (moabu) [inline admin-ui/app/routes/Apps/Gluu/GluuSelectRow.tsx:61]: This grid size calculation is bad because the logic is fundamentally flawed and redundant; the expression `Math.round((lsize / 12) * 12)` will always resolve to `lsize`, adding unnecessary complexity without any functional benefit.)

**Review by moabu — CHANGES_REQUESTED** [review]
minore changes requested

File: admin-ui/app/routes/Apps/Gluu/GluuSelectRow.tsx [hunk 3]
```diff
@@ -46,58 +57,66 @@ function GluuSelectRow({
...
+          <Select
+            labelId={`${name}-label`}
             id={name}
             data-testid={name}
+            size="small"
             name={name}
-            defaultValue={value}
-            onChange={(event: React.ChangeEvent<HTMLInputElement | HTMLSelectElement>) => {
+            value={value || ''}
+            onChange={(event) => {
```
Comment (faisalsiddique4400) [inline admin-ui/app/routes/Apps/Gluu/GluuSelectRow.tsx:90]: On each re-render, this onChange will trigger the code inside of this block,
you can consider putting it with callBack hook.

const handleSelectChange = useCallback((event) => {
  formik.handleChange(event)
  if (handleChange) {
    handleChange(event)
  }
}, [formik.handleChange, handleChange])

and then consider using it like: 
onChange={handleSelectChange}.

this way we can get rid ot re-init the whole event inside this block.

File: admin-ui/app/routes/Apps/Gluu/GluuSelectRow.tsx [hunk 4]
```diff
@@ -46,58 +57,66 @@ function GluuSelectRow({
...
               if (handleChange) {
-                formik.handleChange(event)
                 handleChange(event)
-              } else {
-                formik.handleChange(event)
               }
             }}
-            disabled={disabled}
+            displayEmpty
+            sx={{
```
[the remark this answers is not in the document]
Comment (syntrydy) [reply admin-ui/app/routes/Apps/Gluu/GluuSelectRow.tsx:97]: const selectStyle = useMemo(
    () => ({
      height: '30px',
      minHeight: '30px',
    }),
    [],
  )

File: admin-ui/app/routes/Apps/Gluu/GluuSelectRow.tsx (hunk 3 above)
Comment (syntrydy) [reply admin-ui/app/routes/Apps/Gluu/GluuSelectRow.tsx:90]: const handleSelectChange = useCallback(
    (event: React.ChangeEvent<HTMLInputElement | HTMLSelectElement> | SelectChangeEvent) => {
      formik.handleChange(event)
      if (handleChange) {
        handleChange(event)
      }
    },
    [formik.handleChange, handleChange],
  )

**Review by duttarnab — APPROVED** [review]

**Review by faisalsiddique4400 — APPROVED** [review]

**Review by moabu — APPROVED** [review]
