### PR TITLE
fix(admin-ui): getting blank page for user management #1421

### LINKED ISSUE #1421: fix(admin-ui): getting blank page for user management
**Describe the bug**
getting blank page for user management

**To Reproduce**
1. install flex 5.0.0-20.nightly
2. user
3. click on default admin user  > button

**Expected behavior**
should not get any blank page

**Screenshots**
image

**Desktop (please complete the following information):**
  - OS: ubuntu22
  - flex 5.0.0-20.nighlty
  - DB mysql

**Smartphone (please complete the following information):**

**Additional context**

### PR DESCRIPTION
**Pull request by jv18creator**
closes #1421

### CODE REVIEW

File: admin-ui/app/redux/sagas/AttributesSaga.js [hunk 1]
```diff
@@ -2,24 +2,42 @@ import { call, all, put, fork, takeLatest, select } from 'redux-saga/effects'
...
+import { ATTRIBUTES_TAGS } from 'Utils/PermChecker'
 
 const PERSON_SCHEMA = 'person schema'
 
 const JansConfigApi = require('jans_config_api')
 
 function* newFunction() {
-  const token = yield select((state) => state.authReducer.token.access_token)
+  let token
+  const savedToken = yield select((state) => state.attributesReducerRoot.accessToken)
```
Comment (duttarnab) [inline admin-ui/app/redux/sagas/AttributesSaga.js:25]: `savedToken ` naming is not clear. It can be just `token`. Tak the value directly into the `token` variable if its already present in the redux store.

File: admin-ui/app/utils/PermChecker.js [hunk 2]
```diff
@@ -105,6 +105,7 @@ export const SESSION_READ = BASE_URL + '/jans-auth-server/session.readonly'
 export const SESSION_DELETE = BASE_URL + '/jans-auth-server/session.delete'
 
 export const SCOPE_TAGS = ['scopes']
+export const ATTRIBUTES_TAGS = ['attributes']
```
Comment (duttarnab) [inline admin-ui/app/utils/PermChecker.js:108]: Please do not enclose in the array. Keep it as a string. The string should be added in array whenever required.

There may be cases where multiple tags should added to the array, then this will cause problem.

File: admin-ui/plugins/auth-server/redux/sagas/OAuthScopeSaga.js [hunk 3]
```diff
@@ -38,19 +38,19 @@ import { SCOPE_TAGS } from 'Utils/PermChecker'
 
 function* newFunction() {
   let token
-  const scopesToken = yield select((state) => state.scopeReducer.accessToken)
+  const savedToken = yield select((state) => state.scopeReducer.accessToken)
```
Comment (duttarnab) [inline admin-ui/plugins/auth-server/redux/sagas/OAuthScopeSaga.js:41]: the variable name should be just `token`.

**Review by duttarnab — CHANGES_REQUESTED** [review]
see inline comments.

**Review by duttarnab — APPROVED** [review]
