### PR TITLE
fix(admin-ui): admin UI experiences a loading delay due to the large bundle size of a chunk in the production build

### LINKED ISSUE #2318: fix(admin-ui): admin UI experiences a loading delay due to the large bundle size of a chunk in the production build.
Steps:

1. Create production build of admin-ui (npm run build:prod)
2. 966.bundle.js size is 4112750 bytes due to which it takes more than 1 minute to load admin-ui in incognito mode (i.e. for first time loading of admin-ui on browser).  There are few other chumnks having large size.
```
arnabdutta@Arnabs-MacBook-Air dist % ls -ltr
total 22288
drwxr-xr-x  19 arnabdutta  staff      608 Oct  5 00:24 static
-rw-r--r--   1 arnabdutta  staff     1180 Oct  5 00:24 23.chunk.js
-rw-r--r--   1 arnabdutta  staff     7637 Oct  5 00:24 638.chunk.js
-rw-r--r--   1 arnabdutta  staff     1133 Oct  5 00:24 764.chunk.js
-rw-r--r--   1 arnabdutta  staff   546115 Oct  5 00:24 app.css
-rw-r--r--   1 arnabdutta  staff     1871 Oct  5 00:24 950.chunk.js
-rw-r--r--   1 arnabdutta  staff    11734 Oct  5 00:24 239.chunk.js
-rw-r--r--   1 arnabdutta  staff    15993 Oct  5 00:24 320.chunk.js
-rw-r--r--   1 arnabdutta  staff    28301 Oct  5 00:24 755.chunk.js
-rw-r--r--   1 arnabdutta  staff     5947 Oct  5 00:24 316.chunk.js
-rw-r--r--   1 arnabdutta  staff    48919 Oct  5 00:24 752.chunk.js
-rw-r--r--   1 arnabdutta  staff  2848538 Oct  5 00:24 app.bundle.js
-rw-r--r--   1 arnabdutta  staff  3721938 Oct  5 00:24 25810435ae03a4105797.wasm
-rw-r--r--   1 arnabdutta  staff  4112750 Oct  5 00:24 966.bundle.js
-rw-r--r--   1 arnabdutta  staff     8598 Oct  5 00:24 966.bundle.js.LICENSE.txt
-rw-r--r--   1 arnabdutta  staff     3730 Oct  5 00:24 index.html
-rw-r--r--   1 arnabdutta  staff    19608 Oct  5 00:24 favicon.ico
```

We can resolve this issue using [code splitting](https://legacy.reactjs.org/docs/code-splitting.html).

### PR DESCRIPTION
**Pull request by duttarnab**
closes #2318 

#### Vendor Library Splitting
- **React Ecosystem**: `react`, `react-dom`, `react-router`, `react-router-dom`
- **Material-UI**: `@mui/*`, `@emotion/*`
- **Redux**: `@reduxjs/*`, `redux`, `redux-saga`, `redux-persist`
- **Charts**: `recharts`, `react-ace`, `ace-builds`
- **Utilities**: `lodash`, `moment`, `dayjs`, `axios`, `formik`, `yup`

#### Plugin-based Splitting
- Each plugin gets its own chunk
- Dynamic loading of plugin components
- Fallback mechanisms for failed loads

#### Common Code Splitting
- Shared application code
- Common vendor libraries
- Reusable components

#### Lazy Route Loading
```typescript
// Pre-defined lazy routes
export const LazyRoutes = {
  DashboardPage: createLazyRoute(() => import('../routes/Dashboards/DashboardPage')),
  ProfilePage: createLazyRoute(() => import('../routes/Apps/Profile/ProfilePage')),
  // ... more routes
}
```

#### Usage in Routes
```typescript
<Route
  path="/home/dashboard"
  element={
    <ProtectedRoute>
      <LazyRoutes.DashboardPage />
    </ProtectedRoute>
  }
/>
```

#### Dynamic Plugin Loading
```typescript
// Async plugin loading
export async function processRoutes() {
  const pluginPromises = plugins.map(async (item) => {
    try {
      const metadata = await import(`${item.metadataFile}`)
      return metadata.default.routes || []
    } catch (error) {
      console.warn(`Failed to load plugin routes: ${item.metadataFile}`, error)
      return []
    }
  })
  // ... handle results
}
```

#### Plugin Component Loading
```typescript
// Dynamic plugin component loading
export const loadPluginComponent = (pluginName: string, componentName: string) => {
  return createLazyComponent(() => 
    import(`../../plugins/${pluginName}/components/${componentName}`)
  )
}
```

#### Large Component Splitting
```typescript
// Lazy loading for heavy components
export const LazyComponents = {
  MaterialTable: createLazyComponent(() => import('@material-table/core')),
  ReactAce: createLazyComponent(() => import('react-ace')),
  Recharts: createLazyComponent(() => import('recharts')),
  // ... more components
}
```

#### Conditional Loading
```typescript
// Load components only when needed
<ConditionalComponent
  condition={showChart}
  component={LazyComponents.Recharts}
  fallback={<div>Loading chart...</div>}
/>
```

### CODE REVIEW

**Review by faisalsiddique4400 — APPROVED** [review]

File: admin-ui/app/routes/index.tsx [hunk 1]
```diff
@@ -1,33 +1,38 @@
...
+        console.error('Failed to load plugins:', error)
+        // Fallback to sync loading
+        setPluginMenus(processRoutesSync())
+      } finally {
+        setLoading(false)
+      }
+    }
+
+    loadPlugins()
   }, [])
```
Comment (moabu) [inline admin-ui/app/routes/index.tsx:36]: Remove unused loading state.
loading is set/cleared but never used in render. Drop the state and setLoading calls to reduce noise.

File: admin-ui/app/types/react-grid-layout.d.ts [hunk 2]
```diff
@@ -0,0 +1,90 @@
+declare module 'react-grid-layout' {
+  import { ComponentType } from 'react'
+
```
Comment (moabu) [inline admin-ui/app/types/react-grid-layout.d.ts:3]: Fix missing React namespace import

Line 6 references `React.CSSProperties`, but the React namespace is not imported. Only `ComponentType` is imported from 'react'. This will cause a TypeScript compilation error.



Apply this diff to import the React namespace:

```diff
-  import { ComponentType } from 'react'
+  import * as React from 'react'
+  import { ComponentType } from 'react'
```

Alternatively, use the imported types directly without the namespace:

```diff
   import { ComponentType } from 'react'
+  import type { CSSProperties, ReactNode } from 'react'

   interface GridLayoutProps {
     className?: string
-    style?: React.CSSProperties
+    style?: CSSProperties
     // ... other props
-    children?: React.ReactNode
+    children?: ReactNode
   }
```

File: admin-ui/app/types/react-grid-layout.d.ts [hunk 3]
```diff
@@ -0,0 +1,90 @@
...
+    ) => void
+    onResizeStop?: (
+      layout: any[],
+      oldItem: any,
+      newItem: any,
+      placeholder: any,
+      e: MouseEvent,
+      element: HTMLElement,
+    ) => void
+    onDrop?: (layout: any[], layoutItem: any, e: Event) => void
```
Comment (moabu) [inline admin-ui/app/types/react-grid-layout.d.ts:78]: Verify Event type for onDrop callback.

The `onDrop` callback uses `Event` while all other callbacks use `MouseEvent`. If this is a drag-and-drop event, consider using `DragEvent` for better type specificity.

File: admin-ui/app/types/react-grid-layout.d.ts [hunk 4]
```diff
@@ -0,0 +1,90 @@
...
+    children?: React.ReactNode
+  }
```
Comment (moabu) [inline admin-ui/app/types/react-grid-layout.d.ts:80]: Consider defining proper types instead of `any` to improve type safety.

The interface extensively uses `any` types for layout arrays, items, and event parameters (lines 14, 29-37, 38-45, 46-53, 54-61, 62-69, 70-77, 78). While this is common in third-party declaration files, defining proper interfaces for layout items would provide better type checking and developer experience.



Consider creating typed interfaces for common structures:

```typescript
interface LayoutItem {
  i: string
  x: number
  y: number
  w: number
  h: number
  minW?: number
  minH?: number
  maxW?: number
  maxH?: number
  moved?: boolean
  static?: boolean
  isDraggable?: boolean
  isResizable?: boolean
  resizeHandles?: string[]
  isBounded?: boolean
}

interface GridLayoutProps {
  // ... other props
  layout?: LayoutItem[]
  onLayoutChange?: (layout: LayoutItem[]) => void
  onDragStart?: (
    layout: LayoutItem[],
    oldItem: LayoutItem,
    newItem: LayoutItem,
    placeholder: LayoutItem,
    e: MouseEvent,
    element: HTMLElement,
  ) => void
  // ... similar for other callbacks
}
```

File: admin-ui/app/types/react-grid-layout.d.ts [hunk 5]
```diff
@@ -0,0 +1,90 @@
...
+
+  const Responsive: ComponentType<GridLayoutProps & { breakpoints?: any; responsiveCols?: any }>
+  const ResponsiveGridLayout: ComponentType<
+    GridLayoutProps & { breakpoints?: any; responsiveCols?: any }
+  >
+  const GridLayout: ComponentType<GridLayoutProps>
```
Comment (moabu) [inline admin-ui/app/types/react-grid-layout.d.ts:86]: Replace `any` types with proper interfaces for responsive props.

The `breakpoints` and `responsiveCols` properties use `any` types. Consider defining proper interfaces for these configuration objects to improve type safety.



```typescript
interface Breakpoints {
  lg?: number
  md?: number
  sm?: number
  xs?: number
  xxs?: number
}

interface ResponsiveCols {
  lg?: number
  md?: number
  sm?: number
  xs?: number
  xxs?: number
}

const Responsive: ComponentType<GridLayoutProps & { 
  breakpoints?: Breakpoints
  responsiveCols?: ResponsiveCols 
}>
const ResponsiveGridLayout: ComponentType<GridLayoutProps & { 
  breakpoints?: Breakpoints
  responsiveCols?: ResponsiveCols 
}>
```

File: admin-ui/app/types/react-helmet.d.ts [hunk 6]
```diff
@@ -0,0 +1,20 @@
+declare module 'react-helmet' {
+  import { ComponentType, HelmetData } from 'react-helmet'
```
Comment (moabu) [inline admin-ui/app/types/react-helmet.d.ts:2]: Fix circular import and incorrect type source.

This line has a critical circular import issue: it imports from the same module being declared (`'react-helmet'`). Additionally, `ComponentType` is a React type, not a react-helmet export.



Apply this diff to correct the imports:

```diff
-  import { ComponentType, HelmetData } from 'react-helmet'
+  import { ComponentType, ReactNode } from 'react'
```

Note: If `HelmetData` is required as an export, it should be defined as an interface within this declaration module rather than imported.

File: admin-ui/app/types/react-helmet.d.ts [hunk 7]
```diff
@@ -0,0 +1,20 @@
...
+    title?: string
+    titleTemplate?: string
+    defaultTitle?: string
+    meta?: Array<{ name?: string; property?: string; content: string; httpEquiv?: string }>
+    link?: Array<{ rel?: string; href?: string; type?: string }>
+    script?: Array<{ src?: string; type?: string; innerHTML?: string }>
+    style?: Array<{ type?: string; cssText?: string }>
+    htmlAttributes?: { [key: string]: any }
+    bodyAttributes?: { [key: string]: any }
+    children?: React.ReactNode
```
Comment (moabu) [inline admin-ui/app/types/react-helmet.d.ts:14]: Reference ReactNode instead of React.ReactNode.

Line 14 uses `React.ReactNode` but the React namespace is not imported. After fixing the import on line 2, use `ReactNode` directly.



Apply this diff:

```diff
-    children?: React.ReactNode
+    children?: ReactNode
```

File: admin-ui/app/types/react-helmet.d.ts [hunk 8]
```diff
@@ -0,0 +1,20 @@
...
+  }
+
+  const Helmet: ComponentType<HelmetProps>
+  export default Helmet
+  export { HelmetData }
```
Comment (moabu) [inline admin-ui/app/types/react-helmet.d.ts:19]: Remove unused HelmetData import and export. Delete `HelmetData` from the import on line 2 and remove the `export { HelmetData }` on line 19.

File: admin-ui/app/utils/RouteLoader.tsx [hunk 9]
```diff
@@ -0,0 +1,62 @@
...
+// Route loading utility
+export const createLazyRoute = (importFn: () => Promise<{ default: ComponentType<any> }>) => {
+  const LazyComponent = lazy(importFn)
+
+  return (props: any) => (
+    <Suspense fallback={<GluuSuspenseLoader />}>
+      <LazyComponent {...props} />
+    </Suspense>
+  )
+}
```
Comment (moabu) [inline admin-ui/app/utils/RouteLoader.tsx:13]: Expose preload to make preloadRoute work.

createLazyRoute returns a function component without a preload method, so preloadRoute never does anything. Attach preload = importFn.

```diff
 export const createLazyRoute = (importFn: () => Promise<{ default: ComponentType<any> }>) => {
   const LazyComponent = lazy(importFn)
 
-  return (props: any) => (
-    <Suspense fallback={<GluuSuspenseLoader />}>
-      <LazyComponent {...props} />
-    </Suspense>
-  )
+  const Wrapper: any = (props: any) => (
+    <Suspense fallback={<GluuSuspenseLoader />}>
+      <LazyComponent {...props} />
+    </Suspense>
+  )
+  // Allow preloading the chunk ahead of time
+  Wrapper.preload = importFn
+  return Wrapper
 }
```

File: admin-ui/app/utils/RouteLoader.tsx [hunk 10]
```diff
@@ -0,0 +1,62 @@
...
+// Dynamic route loader for plugins
+export const loadPluginRoute = (pluginName: string, routePath?: string) => {
+  const componentPath = routePath || `${pluginName.charAt(0).toUpperCase() + pluginName.slice(1)}`
+
+  return createLazyRoute(() =>
+    import(`../../plugins/${pluginName}/components/${componentPath}`).catch(() => {
+      // Fallback to index component
+      return import(`../../plugins/${pluginName}/components/index`)
+    }),
+  )
```
Comment (moabu) [inline admin-ui/app/utils/RouteLoader.tsx:48]: Constrain plugin component dynamic import to a known context.

Fully dynamic import path may create an overly broad context chunk. Limit to plugins/*/components/* to keep chunks per plugin.

```diff
-  return createLazyRoute(() =>
-    import(`../../plugins/${pluginName}/components/${componentPath}`).catch(() => {
-      // Fallback to index component
-      return import(`../../plugins/${pluginName}/components/index`)
-    }),
-  )
+  return createLazyRoute(() =>
+    import(
+      /* webpackChunkName: "plugin-[request]" */
+      /* webpackMode: "lazy" */
+      /* webpackInclude: /^[^/]+\/components\/[^/]+$/ */
+      `../../plugins/${pluginName}/components/${componentPath}`
+    ).catch(() =>
+      import(
+        /* webpackChunkName: "plugin-[request]" */
+        /* webpackMode: "lazy" */
+        /* webpackInclude: /^[^/]+\/components\/index(\.(t|j)sx?)?$/ */
+        `../../plugins/${pluginName}/components/index`
+      ),
+    )
+  )
```

File: admin-ui/config/webpack.config.client.dev.ts [hunk 11]
```diff
@@ -30,6 +30,66 @@ const webpackConfig: WebpackConfig & { devServer?: DevServerConfig } = {
...
+        // Plugin chunks - each plugin gets its own chunk
+        plugins: {
+          test: /[\\/]plugins[\\/]/,
+          name: (module: any) => {
+            const pluginName = module.context.match(/[\\/]plugins[\\/]([^\\/]+)[\\/]/)?.[1]
+            return pluginName ? `plugin-${pluginName}` : 'plugin-common'
+          },
+          chunks: 'all',
+          priority: 15,
+        },
```
Comment (moabu) [inline admin-ui/config/webpack.config.client.dev.ts:76]: Guard against undefined module.context in cacheGroup name.

module.context may be undefined (e.g., for CSS/virtual modules), causing a crash. Add a null-safe guard and reuseExistingChunk.

```diff
         plugins: {
           test: /[\\/]plugins[\\/]/,
-          name: (module: any) => {
-            const pluginName = module.context.match(/[\\/]plugins[\\/]([^\\/]+)[\\/]/)?.[1]
-            return pluginName ? `plugin-${pluginName}` : 'plugin-common'
-          },
+          name: (module: any) => {
+            const context = (module && module.context) || ''
+            const match = context && context.match(/[\\/]plugins[\\/]([^\\/]+)[\\/]/)
+            return match && match[1] ? `plugin-${match[1]}` : 'plugin-common'
+          },
           chunks: 'all',
           priority: 15,
+          reuseExistingChunk: true,
         },
```

File: admin-ui/config/webpack.config.client.prod.ts [hunk 12]
```diff
@@ -36,6 +36,63 @@ const webpackConfig: WebpackConfig & { devServer?: DevServerConfig } = {
...
+        // Plugin chunks - each plugin gets its own chunk
+        plugins: {
+          test: /[\\/]plugins[\\/]/,
+          name: (module: any) => {
+            const pluginName = module.context.match(/[\\/]plugins[\\/]([^\\/]+)[\\/]/)?.[1]
+            return pluginName ? `plugin-${pluginName}` : 'plugin-common'
+          },
+          chunks: 'all',
+          priority: 15,
+        },
```
Comment (moabu) [inline admin-ui/config/webpack.config.client.prod.ts:80]: Guard `module.context` before calling `.match`.

`module.context` can be `undefined` (e.g., for concatenated, external, or virtual modules). Calling `.match` on `undefined` will crash the production build. Please add a null check/optional chaining before invoking `.match`. 

```diff
-        plugins: {
+        plugins: {
           test: /[\\/]plugins[\\/]/,
-          name: (module: any) => {
-            const pluginName = module.context.match(/[\\/]plugins[\\/]([^\\/]+)[\\/]/)?.[1]
+          name: (module: any) => {
+            const pluginName = module?.context?.match(/[\\/]plugins[\\/]([^\\/]+)[\\/]/)?.[1]
             return pluginName ? `plugin-${pluginName}` : 'plugin-common'
           },
```

File: admin-ui/plugins/PluginMenuResolver.js [hunk 13]
```diff
@@ -1,22 +1,79 @@
...
+  const pluginPromises = plugins.map(async (item) => {
+    try {
+      const metadata = await import(`${item.metadataFile}`)
+      return metadata.default.menus || []
+    } catch (error) {
+      console.warn(`Failed to load plugin menus: ${item.metadataFile}`, error)
+      return []
+    }
+  })
+
```
Comment (moabu) [inline admin-ui/plugins/PluginMenuResolver.js:16]: Constrain dynamic import context to avoid bundling “everything.”

Fully dynamic import(`${item.metadataFile}`) forces Webpack to create a broad context, inflating chunks. Derive pluginName and use a static base with webpackInclude for per‑plugin chunks.

```diff
-  const pluginPromises = plugins.map(async (item) => {
-    try {
-      const metadata = await import(`${item.metadataFile}`)
-      return metadata.default.menus || []
-    } catch (error) {
-      console.warn(`Failed to load plugin menus: ${item.metadataFile}`, error)
-      return []
-    }
-  })
+  const pluginPromises = plugins.map(async (item) => {
+    try {
+      const pluginName = item.metadataFile?.match(/[\\/]plugins[\\/]([^\\/]+)[\\/]/)?.[1]
+      if (pluginName) {
+        const metadata = await import(
+          /* webpackChunkName: "plugin-[request]" */
+          /* webpackMode: "lazy" */
+          /* webpackInclude: /^\.\/[^/]+\/metadata(\.(t|j)sx?)?$/ */
+          `./${pluginName}/metadata`
+        )
+        return metadata.default.menus || []
+      }
+      // Fallback if path doesn't match expected pattern
+      const metadata = await import(/* webpackIgnore: true */ `${item.metadataFile}`)
+      return metadata.default?.menus || []
+    } catch (error) {
+      console.warn(`Failed to load plugin menus: ${item.metadataFile}`, error)
+      return []
+    }
+  })
```

File: admin-ui/plugins/PluginMenuResolver.js [hunk 14]
```diff
@@ -1,22 +1,79 @@
...
+  const pluginPromises = plugins.map(async (item) => {
+    try {
+      const metadata = await import(`${item.metadataFile}`)
+      return metadata.default.routes || []
+    } catch (error) {
+      console.warn(`Failed to load plugin routes: ${item.metadataFile}`, error)
+      return []
+    }
+  })
```
Comment (moabu) [inline admin-ui/plugins/PluginMenuResolver.js:39]: Apply the same constrained import for routes.

```diff
-  const pluginPromises = plugins.map(async (item) => {
-    try {
-      const metadata = await import(`${item.metadataFile}`)
-      return metadata.default.routes || []
-    } catch (error) {
-      console.warn(`Failed to load plugin routes: ${item.metadataFile}`, error)
-      return []
-    }
-  })
+  const pluginPromises = plugins.map(async (item) => {
+    try {
+      const pluginName = item.metadataFile?.match(/[\\/]plugins[\\/]([^\\/]+)[\\/]/)?.[1]
+      if (pluginName) {
+        const metadata = await import(
+          /* webpackChunkName: "plugin-[request]" */
+          /* webpackMode: "lazy" */
+          /* webpackInclude: /^\.\/[^/]+\/metadata(\.(t|j)sx?)?$/ */
+          `./${pluginName}/metadata`
+        )
+        return metadata.default.routes || []
+      }
+      const metadata = await import(/* webpackIgnore: true */ `${item.metadataFile}`)
+      return metadata.default?.routes || []
+    } catch (error) {
+      console.warn(`Failed to load plugin routes: ${item.metadataFile}`, error)
+      return []
+    }
+  })
```

**Review by moabu — CHANGES_REQUESTED** [review]

File: admin-ui/app/routes/index.tsx (hunk 1 above)
Comment (duttarnab) [reply admin-ui/app/routes/index.tsx:36]: done

File: admin-ui/app/types/react-grid-layout.d.ts (hunk 4 above)
Comment (duttarnab) [reply admin-ui/app/types/react-grid-layout.d.ts:80]: done

Comment (duttarnab) [reply admin-ui/app/types/react-grid-layout.d.ts:80]: done

File: admin-ui/app/utils/RouteLoader.tsx (hunk 10 above)
Comment (duttarnab) [reply admin-ui/app/utils/RouteLoader.tsx:48]: done

File: admin-ui/config/webpack.config.client.prod.ts (hunk 12 above)
Comment (duttarnab) [reply admin-ui/config/webpack.config.client.prod.ts:80]: done

File: admin-ui/plugins/PluginMenuResolver.js (hunk 13 above)
Comment (duttarnab) [reply admin-ui/plugins/PluginMenuResolver.js:16]: done

**Review by moabu — APPROVED** [review]
